
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzcbiylvqemxgvqsdxgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Y2JpeWx2cWVteGd2cXNkeGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDE4NTEsImV4cCI6MjA2MjIxNzg1MX0.JVbRWf-Rrb2EqqSVvCPXANZ1BeBzbeJRfDASaamTDvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
